name: proyectosupermercado
description: A Flutter project for a supermarket app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  provider: ^6.0.4
  fluttertoast: ^8.2.0
  http: ^1.2.2
  flutter_credit_card: ^4.0.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#008000" # Verde de fondo
  image: assets/menu_image.png # Imagen del logo
  android: true
  ios: true
  web: true
  fill: true # Ajusta el tamaño del logo
  android_gravity: center # Centra el logo en Android
  ios_content_mode: scaleAspectFit # Escala el logo en iOS


flutter:
  assets:
    - assets/menu_image.png
    - assets/check.png
  uses-material-design: true
