// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhZ7N5Abkp__sHmuYditwUxImr7VpBlw',
    appId: '1:535240985856:web:79ae1b0e8fbf23f84977e5',
    messagingSenderId: '535240985856',
    projectId: 'supermercado-55228',
    authDomain: 'supermercado-55228.firebaseapp.com',
    storageBucket: 'supermercado-55228.firebasestorage.app',
    measurementId: 'G-33CW056VDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBStHoBKN5QuA8hmyHXJKUu3it4g31IcJI',
    appId: '1:535240985856:android:e1a7941d06d18ea04977e5',
    messagingSenderId: '535240985856',
    projectId: 'supermercado-55228',
    storageBucket: 'supermercado-55228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDi9GcQucxGV9zw-4yeKOnSuSXdl-6nJM',
    appId: '1:535240985856:ios:01b7208422c855c74977e5',
    messagingSenderId: '535240985856',
    projectId: 'supermercado-55228',
    storageBucket: 'supermercado-55228.firebasestorage.app',
    iosBundleId: 'com.supermercado.proyectosupermercado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDi9GcQucxGV9zw-4yeKOnSuSXdl-6nJM',
    appId: '1:535240985856:ios:01b7208422c855c74977e5',
    messagingSenderId: '535240985856',
    projectId: 'supermercado-55228',
    storageBucket: 'supermercado-55228.firebasestorage.app',
    iosBundleId: 'com.supermercado.proyectosupermercado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlhZ7N5Abkp__sHmuYditwUxImr7VpBlw',
    appId: '1:535240985856:web:4c264e2e51f0c38d4977e5',
    messagingSenderId: '535240985856',
    projectId: 'supermercado-55228',
    authDomain: 'supermercado-55228.firebaseapp.com',
    storageBucket: 'supermercado-55228.firebasestorage.app',
    measurementId: 'G-7H301HQJ7J',
  );

}